Template.homeroad.settings = function () {
    return {
        showFilter: true,
        fields: [
            {'key': 'Last Name',
            'label': 'Last Name'},
            {'key': 'First Name',
            'label': 'First Name'},
            {'key': 'End Team',
            'label': 'End Team'},
            {'key': 'Pos',
            'label': 'Pos'},
            {'key': 'hGP',
            'label': 'hGP'},
            {'key': 'hG',
            'label': 'hG'},
            {'key': 'hA',
            'label': 'hA'},
            {'key': 'h+/-',
            'label': 'h+/-'},
            {'key': 'hPIM',
            'label': 'hPIM'},
            {'key': 'hPen',
            'label': 'hPen'},
            {'key': 'hFOW',
            'label': 'hFOW'},
            {'key': 'hFOL',
            'label': 'hFOL'},
            {'key': 'hFO%',
            'label': 'hFO%'},
            {'key': 'hT-QoC',
            'label': 'hT-QoC'},
            {'key': 'hT-DQoC',
            'label': 'hT-DQoC'},
            {'key': 'hT-FQoC',
            'label': 'hT-FQoC'},
            {'key': 'hESOI/G',
            'label': 'hESOI/G'},
            {'key': 'hPPTOI/G',
            'label': 'hPPTOI/G'},
            {'key': 'hSHTOI/G',
            'label': 'hSHTOI/G'},
            {'key': 'hTOI/G',
            'label': 'hTOI/G'},
            {'key': 'hSOS',
            'label': 'hSOS'},
            {'key': 'hSOG',
            'label': 'hSOG'},
            {'key': 'hSO%',
            'label': 'hSO%'},
            {'key': 'hSOGDG',
            'label': 'hSOGDG'},
            {'key': 'rGP',
            'label': 'rGP'},
            {'key': 'rG',
            'label': 'rG'},
            {'key': 'rA',
            'label': 'rA'},
            {'key': 'r+/-',
            'label': 'r+/-'},
            {'key': 'rPIM',
            'label': 'rPIM'},
            {'key': 'rPen',
            'label': 'rPen'},
            {'key': 'rFOW',
            'label': 'rFOW'},
            {'key': 'rFOL',
            'label': 'rFOL'},
            {'key': 'rFO%',
            'label': 'rFO%'},
            {'key': 'rT-QoC',
            'label': 'rT-QoC'},
            {'key': 'rT-DQoC',
            'label': 'rT-DQoC'},
            {'key': 'rT-FQoC',
            'label': 'rT-FQoC'},
            {'key': 'rESTOI/G',
            'label': 'rESTOI/G'},
            {'key': 'rPPTOI/G',
            'label': 'rPPTOI/G'},
            {'key': 'rSHTOI/G',
            'label': 'rSHTOI/G'},
            {'key': 'rTOI/G',
            'label': 'rTOI/G'},
            {'key': 'rSOS',
            'label': 'rSOS'},
            {'key': 'rSOG',
            'label': 'rSOG'},
            {'key': 'rSO%',
            'label': 'rSO%'},
            {'key': 'rSOGDG',
            'label': 'rSOGDG'}
            ]
    };
};


