Template.oniceevents.settings = function () {
    return {
        showFilter: true,
        fields: [{key:'First Name',
                label: 'First Name'},
                {key:'Last Name',
                label: 'Last Name'},
                {key:'Pos',
                label:'Pos'},
                {key:'End Team',
                label:'End Team'},
                  {key: 'GP',
                  label: 'GP'},
                  {key: 'TOI',
                  label: 'TOI'},
                  {key: 'GShr',
                  label: 'GShr'},
                  {key: 'AShr',
                  label: 'AShr'},
                  {key: 'PShr',
                  label: 'PShr'},
                  {key: 'SShr',
                  label: 'SShr'},
                  {key: 'CShr',
                  label: 'CShr'},
                  {key: 'FShr',
                  label: 'FShr'},
                  {key: 'SFDist',
                  label: 'SFDist'},
                  {key: 'SFDistrel',
                  label: 'SFDistrel'},
                  {key: 'SADist',
                  label: 'SADist'},
                  {key: 'SADistrel',
                  label: 'SADistrel'},
                  {key: 'FOW',
                  label: 'FOW'},
                  {key: 'FOL',
                  label: 'FOL'},
                  {key: 'FO%',
                  label: 'FO%'},
                  {key: 'IceDr',
                  label: 'IceDr'},
                  {key: 'IceT',
                  label: 'IceT'},
                  {key: 'IceDr%',
                  label: 'IceDr%'}
            ]
    };
};