Template.possession.settings = function () {
    return {
        showFilter: true,
        fields: [
          {key:'First Name',
          label: 'First Name'},
          {key:'Last Name',
          label: 'Last Name'},
          {key:'Pos',
          label:'Pos'},
          {key:'End Team',
          label:'End Team'},
          {key: 'GP',
          label: 'GP'},
          {key: 'TOI',
          label: 'TOI'},
          {key: 'CF',
          label: 'CF'},
          {key: 'CA',
          label: 'CA'},
          {key: 'CF%',
          label: 'CF%'},
          {key: 'CF%rel',
          label: 'CF%rel'},
          {key: 'FF',
          label: 'FF'},
          {key: 'FA',
          label: 'FA'},
          {key: 'FF%',
          label: 'FF%'},
          {key: 'FF%rel',
          label: 'FF%rel'},
          {key: 'SF',
          label: 'SF'},
          {key: 'SA',
          label: 'SA'},
          {key: 'SF%',
          label: 'SF%'},
          {key: 'SF%rel',
          label: 'SF%rel'},
          {key: 'GF',
          label: 'GF'},
          {key: 'GA',
          label: 'GA'},
          {key: 'GF%',
          label: 'GF%'},
          {key: 'GF%rel',
          label: 'GF%rel'},
          {key: 'Sh%',
          label: 'Sh%'},
          {key: 'Sh%rel',
          label: 'Sh%rel'},
          {key: 'TMSh%',
          label: 'TMSh%'},
          {key: 'Sv%',
          label: 'Sv%'},
          {key: 'Sv%rel',
          label: 'Sv%rel'},
          {key: 'PDO',
          label: 'PDO'},
          {key: 'PDOrel',
          label: 'PDOrel'}
      ]
    };
};